// This file will be generated by the peppermint editor

#ifndef PPMINT_SCRIPTS_SCRIPT_TYPES_H
#define PPMINT_SCRIPTS_SCRIPT_TYPES_H

#include <peppermint/Exceptions.hpp>

#include <peppermint/scripts/TestComponent.h>

#define NUM_SCRIPT_COMPONENT_TYPES 1
#define SCRIPT_COMPONENT_TYPE_1 peppermint::game::components::TestComponent

#define GET_SCRIPT_COMPONENT_TYPE(n) SCRIPT_COMPONENT_TYPE_ ## n
#define GET_SCRIPT_COMPONENT_INDEX(n) n ## _SCRIPT_COMPONENT_INDEX

namespace peppermint {
	namespace scripts {
		peppermint::game::components::ScriptComponent* createScriptComponent(unsigned int scriptType, vector<byte> bytes);
	}
}

#endif